### ISSUE TITLE
create a github workflow for deployment

### ISSUE THREAD

**Issue by foxgem** [TokenScript/tn-token-discovery-api#1]
FYI.

The domain: api.token-discovery.tokenscript.org.

**Comment by abcfy2** [comment]
Done: https://api.token-discovery.tokenscript.org/

CI will be added later.I just manual deploy this API.

**Comment by nicktaras** [comment]
> Done: https://api.token-discovery.tokenscript.org/
> 
> CI will be added later.I just manual deploy this API.

Thanks @abcfy2.

That sounds great to have CI implemented. Can we implement these features into the CI process:

- ensure tests are passing before merge to 'main'
- auto deploy when changes are introduced to the 'main' branch

**Comment by abcfy2** [comment]
@nicktaras Please assign admin permissions to me. I'll set github secrets and push CI to repo.

**Comment by abcfy2** [comment]
@nicktaras CI is done.

You can find the latest CI progress here: https://github.com/TokenScript/tn-token-discovery-api/actions/runs/2361610629

All push an pull request will trigger `build` and `test`. But only push to `main` will trigger `deploy`.

`deploy` only run after both `build` and `test` success.

**Comment by nicktaras** [comment]
Amazing work on this, thanks.
